import * as React from "react";
import { StaticImage } from "gatsby-plugin-image";
import Layout from "../components/layout";
import { SEO } from '../components/seo'


const IndexPage = () => {
  return (
    <main>
      <Layout pageTitle="Home Page">
        <p>Hey👋🏻 this is Efe, and this is my blog where I write about stuff I find interesting.</p>
        <p>Here's a totally random drawing I like, which I generated by AI(ofc)</p>
        <StaticImage alt="Cottage in impressionist style" src="../images/cottage.png" />
      </Layout>
    </main>
  );
};

export default IndexPage;

export const Head = () => <SEO />
